### ISSUE TITLE
Why to delete your babel.config.js file ?

### ISSUE THREAD

**Issue by mohan-win** [martinmoec/fable-react-native-how-to#1]
Hi, Thanks a lot for the detailed steps. Wondering why we need to delete the babel.config.js ?

**Comment by retendo** [comment]
I second this question ;) It actually produces errors.

**Comment by martinmoec** [comment]
Sorry, i did not notice this issue until @retendo commented! You do not need to delete your babel.config.js file, but in my experience its the easiest and fastest way to get up an running. Note that i do not really have a strong Babel expertise, at all, and someone with a better understanding could probably provide you with better info and a better setup. The how-to should however be updated to reflect this, as the current wording implies deleting the file is a requirement.

**Comment by playfulThinking** [comment]
This seems to fix the errors: https://github.com/SAFE-Stack/SAFE-Nightwatch/issues/74#issuecomment-590006420

**Comment by martinmoec** [comment]
I have included `filename: "App.js"` in the splitter configuration in 8c6e340 and the error is no longer present while still including the `babel.config.js` file. As you can see [here](https://babeljs.io/docs/en/options#filename) parts of Babels functionality is not available when the filename is unknown.
