### ISSUE TITLE
Either `undefined` or `object` important, resulting into an error

### ISSUE THREAD

**Issue by bhootd** [martinmoec/fable-react-native-how-to#5]
In `index.js`, putting

`import * as App from './out/App.js'` gives `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

`import App from './out/App.js'` gives `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

`import {App} from './out/App.js'` gives `Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

From the last two, it seems `App` is not marked as an export at all. Am I doing something wrong?

**Comment by bhootd** [comment]
Ah! I figured it out. I'm supposed to remove the component registration from `index.js`:

So `index.js` turns from:

```
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

to:

```
/**
 * @format
 */

import {AppRegistry} from 'react-native';
import * as App from './out/App.js';
import {name as appName} from './app.json';
```

**Comment by bhootd** [comment]
@martinmoec while the instructions at https://github.com/martinmoec/fable-react-native-how-to#importing-the-generated-javascript are technically clear enough in hindsight, could you also explicitly instruct the user to remove the component registration line `AppRegistry.registerComponent(appName, () => App);` from `index.js`?

**Comment by martinmoec** [comment]
Hi!
Sure, i will update the how-to so that this becomes clearer.
